export { default as User } from "./User";
export { default as Company } from "./Company";
export { default as Contact } from "./Contact";
export { default as Funnel } from "./Funnel";
export { default as Deal } from "./Deal";
export { default as Product } from "./Product";
export { default as Transaction } from "./Transaction";
export { default as Task } from "./Task";
export { default as NPSRating } from "./NPSRating";
export { default as NPSSurvey } from "./NPSSurvey";
export { default as NPSInvite } from "./NPSInvite";
export { default as Form } from "./Form";
export { default as FormInvite } from "./FormInvite";
export { default as FormResponse } from "./FormResponse";
export { default as Label } from "./Label";
export { default as FinancialCategory } from "./FinancialCategory";
export { default as Notification } from "./Notification";
export { default as NoteGroup } from "./NoteGroup";
export { default as Note } from "./Note";
export { default as GoogleConnection } from "./GoogleConnection";

export type { IUser } from "./User";
export type { ICompany } from "./Company";
export type { IContact } from "./Contact";
export type { IFunnel, IFunnelStage } from "./Funnel";
export type { IDeal, IDealNote, IDealDossier } from "./Deal";
export type { IProduct } from "./Product";
export type { ITransaction, IProductCalculation, ITransactionDistribution } from "./Transaction";
export type { ITask } from "./Task";
export type { INPSRating } from "./NPSRating";
export type { INPSSurvey } from "./NPSSurvey";
export type { INPSInvite } from "./NPSInvite";
export type { IForm, IFormField } from "./Form";
export type { IFormInvite, FormInviteStatus } from "./FormInvite";
export type { IFormResponse, IFormAnswer } from "./FormResponse";
export type { ILabel } from "./Label";
export type { IFinancialCategory } from "./FinancialCategory";
export type { INotification } from "./Notification";
export type { INoteGroup } from "./NoteGroup";
export type { INote, INoteShare } from "./Note";
export type { IGoogleConnection } from "./GoogleConnection";
